// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _05_Fiap.Web.AspNet.Persistences;

namespace _05Fiap.Web.AspNet.Migrations
{
    [DbContext(typeof(AllZooContext))]
    [Migration("20190902133917_BancoInicio")]
    partial class BancoInicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_05_Fiap.Web.AspNet.Models.Zoo", b =>
                {
                    b.Property<int>("Zooo")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataAbertura");

                    b.Property<int>("EntidadeAdministradora");

                    b.Property<int>("Jaulas");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Zooo");

                    b.ToTable("TB_ZOO");
                });
#pragma warning restore 612, 618
        }
    }
}
